# Generated by Django 3.2.13 on 2022-06-23 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruposProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField()),
                ('qtde_estoque', models.PositiveIntegerField()),
                ('chavegrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gruposprodutos')),
            ],
        ),
        migrations.CreateModel(
            name='Promo_Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fim_promo', models.DurationField()),
                ('taxadesconto', models.FloatField()),
                ('chave_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produtos')),
            ],
        ),
    ]
