# Generated by Django 3.2.13 on 2022-06-24 03:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_acesso', models.CharField(max_length=45, unique=True)),
                ('senha_acesso', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('cel', models.CharField(blank=True, max_length=14, null=True)),
                ('situacao_conta', models.BooleanField(default=True)),
                ('cep', models.CharField(max_length=9)),
                ('rua_ondemora', models.TextField(max_length=255)),
                ('num_casa', models.PositiveIntegerField(default=0)),
                ('bairro_ondemora', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=2)),
                ('ponto_referencia', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formas_pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='promo_produtos',
            name='inicio_promo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo_produtos',
            name='fim_promo',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('qtde_parcelamento', models.PositiveIntegerField(default=1)),
                ('entrada_avista', models.FloatField(default=0.0)),
                ('desconto', models.FloatField(default=0.0)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientes')),
                ('id_forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.formas_pagamentos')),
            ],
        ),
    ]
