# Generated by Django 3.2.13 on 2022-06-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='bairro_ondemora',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(max_length=45, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Celular/Watsaap'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='num_casa',
            field=models.PositiveIntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ponto_referencia',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ponto de referência'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='rua_ondemora',
            field=models.TextField(max_length=255, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='senha_acesso',
            field=models.CharField(max_length=45, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='user_acesso',
            field=models.CharField(max_length=45, unique=True, verbose_name='Usuario'),
        ),
    ]
