# Generated by Django 3.2.13 on 2022-07-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220630_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Celular/Watsaap'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='user_acesso',
            field=models.CharField(max_length=45, unique=True, verbose_name='Usuário'),
        ),
    ]
