# Generated by Django 3.2.13 on 2022-07-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220701_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='num_casa',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
