# Generated by Django 3.2.13 on 2022-07-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_clientes_num_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='num_casa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
    ]
