# Generated by Django 3.2.13 on 2022-07-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_clientes_num_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.PositiveIntegerField(max_length=8, verbose_name='Código Postal'),
        ),
    ]
