# Generated by Django 3.2.13 on 2022-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_clientes_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='Código Postal'),
        ),
    ]
