# Generated by Django 3.2.13 on 2022-07-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_produtos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular/Watsaap'),
        ),
    ]
