# Generated by Django 3.2.13 on 2022-07-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_clientes_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='photo',
            field=models.ImageField(default='foto-produto', upload_to='produtos'),
        ),
    ]
