# Generated by Django 3.2.13 on 2022-07-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_produtos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='photo',
            field=models.ImageField(default='foto-produto', height_field='500px', max_length=250, upload_to='produtos', width_field='300px'),
        ),
    ]
