# Generated by Django 3.2.13 on 2022-07-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_produtos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='photo',
        ),
        migrations.AddField(
            model_name='produtos',
            name='img-foto',
            field=models.ImageField(default='foto-produto', height_field='500', max_length=250, upload_to='produtos', verbose_name='Imagem do Produto', width_field='300'),
        ),
    ]
