# Generated by Django 3.2.13 on 2022-07-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_produtos_img-foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='img-foto',
            new_name='img_foto',
        ),
    ]
