# Generated by Django 3.2.13 on 2022-07-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_img-foto_produtos_img_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='img_foto',
            field=models.ImageField(default='foto-produto', max_length=250, upload_to='produtos', verbose_name='Imagem do Produto'),
        ),
    ]
