# Generated by Django 3.2.13 on 2022-07-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_produtos_img_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tag_descricao',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Breve descrição do produto.'),
        ),
    ]
