# Generated by Django 3.2.13 on 2022-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_produtos_tag_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produtos',
            name='destaques',
            field=models.TextField(blank=True, null=True, verbose_name='Destaques do produto.'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='ficha_tecnica',
            field=models.TextField(blank=True, null=True, verbose_name='Ficha Técnica do produto.'),
        ),
    ]
