# Generated by Django 3.2.13 on 2022-07-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220720_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoproduto_correios',
            fields=[
                ('myproduto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.produtos', verbose_name='Chave do Produtos')),
                ('peso', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Peso total da encomenda')),
                ('formato', models.PositiveIntegerField(choices=[(1, 'Formato caixa/pacote'), (2, 'Formato rolo/prisma'), (3, 'Envelope')], verbose_name='Tipo de encomenda')),
                ('comprimento', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Comprimento da encomenda')),
                ('altura', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Altura da encomenda')),
                ('largura', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Largura da encomenda')),
                ('diametro', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Diametro da encomenda')),
            ],
        ),
    ]
